version: 1.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- nuget restore
build:
  project: ConsoleApplication1\ConsoleApplication1.sln
  parallel: true
  verbosity: normal
test:
  assemblies: 'Tests.dll'
